spring.application.name=api-gateway
server.port=8084

# Keycloak Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/aegis

# Spring Cloud Gateway MVC Routes
spring.cloud.gateway.mvc.routes[0].id=core-banking
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/core/**
spring.cloud.gateway.mvc.routes[0].filters[0]=MapRequestHeader=Authorization, Authorization

spring.cloud.gateway.mvc.routes[1].id=fraud-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/fraud/**
spring.cloud.gateway.mvc.routes[1].filters[0]=MapRequestHeader=Authorization, Authorization

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Vault Configuration
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=root
spring.config.import=vault://

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=16379
